Controllers/ACommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MyStackOverFlow.Models;

namespace MyStackOverFlow.Controllers
{
    public class ACommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AComments
        public ActionResult Index(int? id)
        {
            //var aComments = db.AComments.Include(a => a.Answer).Include(a => a.User);
            var aComments = db.AComments.Where(Ac => Ac.AnswerId == id);
              return View(aComments.ToList());
          
        }

        // GET: AComments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AComment aComment = db.AComments.Find(id);
            if (aComment == null)
            {
                return HttpNotFound();
            }
            return View(aComment);
        }

        // GET: AComments/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: AComments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Description")] AComment aComment, int? id)
        {
            aComment.UserId = this.User.Identity.GetUserId();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            aComment.AnswerId= id;
            aComment.Comdate = DateTime.Now;
            db.AComments.Add(aComment);
            db.SaveChanges();
           
            return RedirectToAction("Details/" , "Questions", new { id = id.ToString(), viewtype = "extended" });
           
        }

        // GET: AComments/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AComment aComment = db.AComments.Find(id);
            if (aComment == null)
            {
                return HttpNotFound();
            }
            ViewBag.AnswerId = new SelectList(db.Answers, "Id", "Description", aComment.AnswerId);
       
            return View(aComment);
        }

        // POST: AComments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Description,Comdate,AnswerId,UserId")] AComment aComment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aComment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AnswerId = new SelectList(db.Answers, "Id", "Description", aComment.AnswerId);
            ViewBag.UserId = new SelectList(db.ApplicationUsers, "Id", "Email", aComment.UserId);
            return View(aComment);
        }

        // GET: AComments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AComment aComment = db.AComments.Find(id);
            if (aComment == null)
            {
                return HttpNotFound();
            }
            return View(aComment);
        }

        // POST: AComments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AComment aComment = db.AComments.Find(id);
            db.AComments.Remove(aComment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MyStackOverFlow.Models;

namespace MyStackOverFlow.Controllers
{
    public class AnswersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Answers
        public ActionResult Index()
        {
            var answers = db.Answers.Include(a => a.Question).Include(a => a.User);
            return View(answers.ToList());
        }

        // GET: Answers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }

        [Authorize]
        // GET: Answers/Create
        public ActionResult CreateAns()
        {
            return View();
        }

        // POST: Answers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]

        public ActionResult CreateAns([Bind(Include = "Id,Description,Ansdate")]  Answer answer, int? id)
        {
            answer.UserId = this.User.Identity.GetUserId();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            answer.QuestionId = id;
            answer.AnsVoteCount = 0;
            answer.Ansdate = DateTime.Now;
            db.Answers.Add(answer); 
            db.SaveChanges();

            return RedirectToAction("Details/", "Questions", new { id = id.ToString(), viewtype = "extended" });
        }

        // GET: Answers/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Tilte", answer.QuestionId);
            ViewBag.UserId = new SelectList(db.ApplicationUsers, "Id", "Email", answer.UserId);
            return View(answer);
        }

        // POST: Answers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Description,Ansdate,AnsVoteCount,UserId,QuestionId")] Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(answer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Tilte", answer.QuestionId);
            ViewBag.UserId = new SelectList(db.ApplicationUsers, "Id", "Email", answer.UserId);
            return View(answer);
        }

        // GET: Answers/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }

        // POST: Answers/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Answer answer = db.Answers.Find(id);
            db.Answers.Remove(answer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyStackOverFlow.Models;

namespace MyStackOverFlow.Controllers
{
    public class TagsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Tags
        public ActionResult Index()
        {
            return View(db.Tags.ToList());
        }

        // GET: Tags/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }


            var Result = db.Questions.Where(q => q.Tag.Any(t => t.TagId == id)).ToList();
            return View(Result);
        }

        // GET: Tags/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TagId,Title")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Tags.Add(tag);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tag);
        }

        // GET: Tags/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TagId,Title")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tag).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tag);
        }

        // GET: Tags/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tag tag = db.Tags.Find(id);
            db.Tags.Remove(tag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/VotesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyStackOverFlow.Models;

namespace MyStackOverFlow.Controllers
{
    public class VotesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Votes
        public ActionResult Index()
        {
            var votes = db.Votes.Include(v => v.Answer).Include(v => v.Question);
            return View(votes.ToList());
        }

        // GET: Votes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vote vote = db.Votes.Find(id);
            if (vote == null)
            {
                return HttpNotFound();
            }
            return View(vote);
        }

        // GET: Votes/Create
        public ActionResult CreateQUpVote()
        {
            return View();
        }

        // POST: Votes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateQUpVote([Bind(Include = "Id,UpVote")] Vote vote, int id)
        {
                vote.QuestionId = id;
                vote.UpVote = true;
                db.Votes.Add(vote);
                db.SaveChanges();
         //   return View("Details", "Questions");
                return RedirectToAction("Details/", "Questions", new { id = id.ToString(), viewtype = "extended" });
        }

        // GET: Votes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vote vote = db.Votes.Find(id);
            if (vote == null)
            {
                return HttpNotFound();
            }
            ViewBag.AnswerId = new SelectList(db.Answers, "Id", "Description", vote.AnswerId);
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Tilte", vote.QuestionId);
            return View(vote);
        }

        // POST: Votes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UpVote,DownVote,QuestionId,AnswerId")] Vote vote)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vote).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AnswerId = new SelectList(db.Answers, "Id", "Description", vote.AnswerId);
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Tilte", vote.QuestionId);
            return View(vote);
        }

        // GET: Votes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vote vote = db.Votes.Find(id);
            if (vote == null)
            {
                return HttpNotFound();
            }
            return View(vote);
        }

        // POST: Votes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vote vote = db.Votes.Find(id);
            db.Votes.Remove(vote);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/Details.cshtml
@model MyStackOverFlow.Models.Question


<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="BaseLayout.css" type="text/css" />
    <title>Wehry Home Page</title>


    <link href="~/Styles.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <br />
    <h2>Details</h2>
    <div class="main">
        <div>@Model.Tilte</div>
        <div>Posted By:  @Model.User.UserName  &nbsp; &nbsp; Date : @Model.Qdate </div>
        <div>Description : </div>
        <div>@Model.Description</div>
        <br />
        <div class="ans">

            @{
                int count = 1;

                foreach (var ans in Model.Answers)
                {
                    <div> Answer @count </div>

                    <div>@ans.Description </div>
                    <div>
                        <span class="qdetail">
                            Answered by : @ans.User.UserName &nbsp; &nbsp; Date : @ans.Ansdate
                            &nbsp; &nbsp; Votes : @ans.AnsVoteCount  &nbsp; &nbsp;
                            @Html.ActionLink("View Comments", "Index", "AComments", new { id = Model.Id }, null)
                            @Html.ActionLink("Any Comments?", "Create", "AComments", new { id = Model.Id }, null)
                        </span>
                    </div>
                    count++;
                }
            }
        </div>

        <br />
        <br />
        <div>
            @foreach (var tag in Model.Tag)
            {
                string MyTag = @tag.Title;

                <span>
                    &nbsp;&nbsp;
                    @Html.ActionLink(MyTag, "Details", "Tags", new { id = tag.TagId }, null)

                </span>
            }
            <span>&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;Votes : @Model.QVoteCount</span>
        </div>
        <br />
        <div>

            @Html.ActionLink("Post A Answer", "CreateAns", "Answers", new { id = Model.Id }, null) |
            @Html.ActionLink("Comment", "Create", "QComments", new { id = Model.Id }, null) |
            @Html.ActionLink("VoteUp", "CreateQUpVote", "Votes", new { id = Model.Id }, null)
        </div>
      
    </div>
</body>
</html>

Views/Shared/MyLayOut.cshtml
<!DOCTYPE html>
@using Microsoft.AspNet.Identity

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" media="screen" type="text/css" href="~/Content/NewStyles.css" />
    <meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
</head>



<body>
    <div id="container">
        <div id="body_space">
            <div id="header">
                <div id="logo-block">
                    <!-- type your logo and small slogan here -->
                    <p id="logo">My<span class="logoblue">StackOverFlow</span></p>
                    <p id="slogan">Help On The Way</p>
                    <!-- end logo and small slogan -->
                </div>
                <!-- login -->
                <div id="login_top">
                    <p>login:&nbsp;&nbsp;</p>

                    @if (Request.IsAuthenticated)
                    {

                        using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                        {
                            @Html.AntiForgeryToken()

                            <ul class="nav navbar-nav navbar-right">
                                <li>
                                    @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                                </li>
                                <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                            </ul>
                        }
                    }
                    else
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                            <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                        </ul>
                    }
                    <!-- end login -->
                    <!-- search -->
                    <!-- end search -->
                </div>
                <div id="definels">

                    <div class="cls"></div>
                    <div id="top-nav-bg">
                        <div id="top-nav">
                            <!-- start top navigation bar -->
                            <ul class="nav navbar-nav">
                                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                <li>@Html.ActionLink("About", "About", "Home")</li>
                                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            </ul>
                            @Html.Partial("_LoginPartial")
                            <!-- end top navigation bar -->
                        </div>
                    </div>
                </div>
                <div id="clouds">
                    <!-- large slogan here -->
                    <div id="clouds-slogan1"><p>a very large website slogan</p></div>
                    <div id="clouds-slogan2"><p>can be placed in this area</p></div>
                    <!-- end large slogan -->
                </div>
            </div>
        </div>








        <div>
            @RenderBody()
        </div>

/*
        <div id="footer">
            <div id="footer-pad">
                <div class="line"></div>
                <!-- footer and copyright notice -->
                <p>This site is &copy; Copyright website My StackOverFlow All rights reserved. </p>
                <!-- end footer and copyright notice -->
            </div>
        </div>*/
    </div>

</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My StackOverFlow</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" media="screen" type="text/css" href="~/Styles.css" />

</head>
<body>
    <div>
        @RenderBody()
    </div>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My StackOverFlow", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Questions", "Index", "Questions")</li>
                    <li>@Html.ActionLink("Managment", "AssignRole", "MemberHelper")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_MyLayOut.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" media="screen" type="text/css" href="~/Content/MyStyles.css" />
    <meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
</head>


   
<body>
    <div id="container">
        <div id="body_space">
            <div id="header">
                <div id="logo-block">
                    <!-- type your logo and small slogan here -->
                    <p id="logo">My<span class="logoblue">StackOverFlow</span></p>
                    <p id="slogan">Help On The Way</p>
                    <!-- end logo and small slogan -->
                </div>

                <div id="definels">
                    <!-- login -->
                    <div id="login_top">
                        <p>login:&nbsp;&nbsp;</p>
                        <form name="login" method="get" action="" target="_parent">
                            <input name="name" type="text" value="username" class="topinputstyle" />
                            <p>&nbsp;&nbsp;</p>
                            <div class="formspace"><input name="email" type="text" value="password" class="topinputstyle" /></div>
                            <p>&nbsp;&nbsp;</p>
                            <div class="formspace"><input type="submit" value="" class="loginbutton" /></div>
                        </form>
                    </div>
                    <!-- end login -->
                    <!-- search -->
                    <div id="search">
                        <form name="search" method="get" action="" target="_parent">
                            <input type="text" class="box" />
                            <button class="btn" title="Submit Search">Search</button>
                        </form>
                    </div>
                    <!-- end search -->
                </div>
                <div class="cls"></div>
                <div id="top-nav-bg">
                    <div id="top-nav">
                        <!-- start top navigation bar -->
                        <ul>
                            <li><a href="http://www.webaddresshere.com">Home</a></li>
                            <li><a href="http://www.webaddresshere.com">Products</a></li>
                            <li><a href="http://www.webaddresshere.com">Services</a></li>
                            <li><a href="http://www.webaddresshere.com">Portfolio</a></li>
                            <li><a href="http://www.webaddresshere.com">About Us</a></li>
                            <li><a href="http://www.webaddresshere.com">Contact</a></li>
                            <li><a style="background-image: none;" href="http://www.webaddresshere.com">Support</a></li>
                        </ul>
                        <!-- end top navigation bar -->
                    </div>
                </div>
            </div>
            <div id="clouds">
                <!-- large slogan here -->
                <div id="clouds-slogan1"><p>a very large website slogan</p></div>
                <div id="clouds-slogan2"><p>can be placed in this area</p></div>
                <!-- end large slogan -->
            </div>
        </div>
    </div>
    <div>
        @RenderBody()
    </div>


    <div id="footer">
        <div id="footer-pad">
            <div class="line"></div>
            <!-- footer and copyright notice -->
            <p>This site is &copy; Copyright website My StackOverFlow All rights reserved. </p>
            <!-- end footer and copyright notice -->
        </div>
    </div>



</body>
</html>

Views/Shared/_MyLayOut2.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" media="screen" type="text/css" href="~/Content/MyStyles.css" />
    <meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
</head>



<body>          
                <div id="top-nav-bg">
                    <div id="top-nav">
                        <!-- start top navigation bar -->
                        <ul>
                            <li><a href="http://www.webaddresshere.com">Home</a></li>
                            <li><a href="http://www.webaddresshere.com">Products</a></li>
                            <li><a href="http://www.webaddresshere.com">Services</a></li>
                            <li><a href="http://www.webaddresshere.com">Portfolio</a></li>
                            <li><a href="http://www.webaddresshere.com">About Us</a></li>
                            <li><a href="http://www.webaddresshere.com">Contact</a></li>
                            <li><a style="background-image: none;" href="http://www.webaddresshere.com">Support</a></li>
                        </ul>
                        <!-- end top navigation bar -->
                    </div>
                </div>
           
         
    <div>
        @RenderBody()
    </div>




</body>
</html>