Controllers/ACommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MyStackOverFlow.Models;

namespace MyStackOverFlow.Controllers
{
    public class ACommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AComments
        public ActionResult Index(int? id)
        {
            //var aComments = db.AComments.Include(a => a.Answer).Include(a => a.User);
            var aComments = db.AComments.Where(Ac => Ac.AnswerId == id);
              return View(aComments.ToList());
          
        }

        // GET: AComments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AComment aComment = db.AComments.Find(id);
            if (aComment == null)
            {
                return HttpNotFound();
            }
            return View(aComment);
        }

        // GET: AComments/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: AComments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Description")] AComment aComment, int? id)
        {
            aComment.UserId = this.User.Identity.GetUserId();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            aComment.AnswerId= id;
            aComment.Comdate = DateTime.Now;
            db.AComments.Add(aComment);
            db.SaveChanges();
           
            return RedirectToAction("Details/" , "Questions", new { id = id.ToString(), viewtype = "extended" });
           
        }

        // GET: AComments/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AComment aComment = db.AComments.Find(id);
            if (aComment == null)
            {
                return HttpNotFound();
            }
            ViewBag.AnswerId = new SelectList(db.Answers, "Id", "Description", aComment.AnswerId);
       
            return View(aComment);
        }

        // POST: AComments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Description,Comdate,AnswerId,UserId")] AComment aComment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aComment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AnswerId = new SelectList(db.Answers, "Id", "Description", aComment.AnswerId);
            ViewBag.UserId = new SelectList(db.ApplicationUsers, "Id", "Email", aComment.UserId);
            return View(aComment);
        }

        // GET: AComments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AComment aComment = db.AComments.Find(id);
            if (aComment == null)
            {
                return HttpNotFound();
            }
            return View(aComment);
        }

        // POST: AComments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AComment aComment = db.AComments.Find(id);
            db.AComments.Remove(aComment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MyStackOverFlow.Models;

namespace MyStackOverFlow.Controllers
{
    public class AnswersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Answers
        public ActionResult Index()
        {
            var answers = db.Answers.Include(a => a.Question).Include(a => a.User);
            return View(answers.ToList());
        }

        // GET: Answers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }

        [Authorize]
        // GET: Answers/Create
        public ActionResult CreateAns()
        {
            return View();
        }

        // POST: Answers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]

        public ActionResult CreateAns([Bind(Include = "Id,Description,Ansdate")]  Answer answer, int? id)
        {
            answer.UserId = this.User.Identity.GetUserId();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            answer.QuestionId = id;
            answer.AnsVoteCount = 0;
            answer.Ansdate = DateTime.Now;
            db.Answers.Add(answer); 
            db.SaveChanges();

            return RedirectToAction("Details/", "Questions", new { id = id.ToString(), viewtype = "extended" });
        }

        // GET: Answers/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Tilte", answer.QuestionId);
            ViewBag.UserId = new SelectList(db.ApplicationUsers, "Id", "Email", answer.UserId);
            return View(answer);
        }

        // POST: Answers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Description,Ansdate,AnsVoteCount,UserId,QuestionId")] Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(answer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Tilte", answer.QuestionId);
            ViewBag.UserId = new SelectList(db.ApplicationUsers, "Id", "Email", answer.UserId);
            return View(answer);
        }

        // GET: Answers/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }

        // POST: Answers/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Answer answer = db.Answers.Find(id);
            db.Answers.Remove(answer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/QCommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MyStackOverFlow.Models;

namespace MyStackOverFlow.Controllers
{
    public class QCommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: QComments
        public ActionResult Index()
        {
            var qComments = db.QComments.Include(q => q.Question).Include(q => q.User);
            return View(qComments.ToList());
        }

        // GET: QComments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QComment qComment = db.QComments.Find(id);
            if (qComment == null)
            {
                return HttpNotFound();
            }
            return View(qComment);
        }

        // GET: QComments/Create
        [Authorize]
        public ActionResult Create()
        {
           
            return View();
        }

        // POST: QComments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Description")] QComment qComment, int id)
        {
            qComment.UserId = this.User.Identity.GetUserId();
            qComment.QuestionId = id;

                qComment.Comdate = DateTime.Now;
                db.QComments.Add(qComment);
                db.SaveChanges();

            return RedirectToAction("Details/", "Questions", new { id = id.ToString(), viewtype = "extended" });

        }

        // GET: QComments/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QComment qComment = db.QComments.Find(id);
            if (qComment == null)
            {
                return HttpNotFound();
            }
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Tilte", qComment.QuestionId);
            ViewBag.UserId = new SelectList(db.ApplicationUsers, "Id", "Email", qComment.UserId);
            return View(qComment);
        }

        // POST: QComments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Description,Comdate,QuestionId,UserId")] QComment qComment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(qComment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Tilte", qComment.QuestionId);
            ViewBag.UserId = new SelectList(db.ApplicationUsers, "Id", "Email", qComment.UserId);
            return View(qComment);
        }

        // GET: QComments/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QComment qComment = db.QComments.Find(id);
            if (qComment == null)
            {
                return HttpNotFound();
            }
            return View(qComment);
        }

        // POST: QComments/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            QComment qComment = db.QComments.Find(id);
            db.QComments.Remove(qComment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyStackOverFlow.Models;

namespace MyStackOverFlow.Controllers
{
    public class TagsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Tags
        public ActionResult Index()
        {
            return View(db.Tags.ToList());
        }

        // GET: Tags/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }


            var Result = db.Questions.Where(q => q.Tag.Any(t => t.TagId == id)).ToList();
            return View(Result);
        }

        // GET: Tags/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TagId,Title")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Tags.Add(tag);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tag);
        }

        // GET: Tags/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TagId,Title")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tag).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tag);
        }

        // GET: Tags/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tag tag = db.Tags.Find(id);
            db.Tags.Remove(tag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Questions/Create.cshtml
@model MyStackOverFlow.Models.Question
  
<h3>Ask a Question Here</h3>
<@ViewBag.TagId>
    <@ViewBag.TagId2>


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Tilte, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Tilte, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Tilte, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                &nbsp;&nbsp;  &nbsp;&nbsp; &nbsp;&nbsp;  &nbsp;&nbsp;
                <div>
                    <b> Please Select Most Relevant Tags</b>


                    &nbsp;&nbsp;  &nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;  Tag1 :   @Html.DropDownList("TagId", (SelectList)ViewBag.TagId, "Select one")

                    &nbsp;&nbsp;&nbsp;  Tag2 :   @Html.DropDownList("TagId2", (SelectList)ViewBag.TagId2, "Select 2nd")
                </div>


            </div>



            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    &nbsp;&nbsp;&nbsp;     <input type="submit" value="Post Question " class="btn btn-default" 
    width: 20em;  height: 2em; />
                </div>
            </div>
            <div>  @ViewBag.Message </div>
        </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

Views/Questions/Delete.cshtml
@model MyStackOverFlow.Models.Question

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tilte)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tilte)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Qdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Qdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QVoteCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QVoteCount)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Questions/Details.cshtml
@model MyStackOverFlow.Models.Question
   

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="BaseLayout.css" type="text/css" />
    <title>Wehry Home Page</title>
    <script><link rel="stylesheet" href="https://icons8.com/icon/116997/prize"></link></script>


    <link href="~/Styles.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <br />
    <h2>Answers</h2>
    <div class="main">
        <br />
        <div style="margin-left:5px">Question: @Model.Tilte</div>
        <div style="margin-left:5px">Posted By:  @Model.User.UserName  &nbsp; &nbsp; Date : @Model.Qdate.ToShortDateString() </div>
        <div style="margin-left:5px">Description : <span style="margin-left:5px">@Model.Description</span> </div>
        
        <br />
   
     

        <div class="ans1">

            @{
                int count = 1;
                foreach (var ans in Model.Answers)
                {

                    <div class="ansDetails" style="flex-grow: 5">
                        <div> <b>Answer</b> @count </div>

                        <div>@ans.Description </div>
                        <div>
                            <span class="qdetail">
                                by : @ans.User.UserName  &nbsp;
                                @if(ans.User.Badge != null){
                                <img src=@ans.User.Badge style="height : 30px;width : 30px;" />
                                }


                                &nbsp;&nbsp;   Date : @ans.Ansdate.ToShortDateString()
                                &nbsp; &nbsp; Votes : @ans.AnsVoteCount  &nbsp; &nbsp;



                            </span>
                       
                            <div>

                                @Html.ActionLink("View Comments", "Index", "AComments", new { id = Model.Id }, null)|
                                @Html.ActionLink("Any Comments?", "Create", "AComments", new { id = Model.Id }, null)

                                &nbsp; &nbsp;  &nbsp; &nbsp;  &nbsp; &nbsp;&nbsp;  &nbsp; &nbsp;
                                @Html.ActionLink("UpVote", "CreateAnsUpVote", "MemberHelper", new { qid = Model.Id, ansid = ans.Id }, null) |
                                @Html.ActionLink("DownVote", "CreateAnsDownVote", "MemberHelper", new { qid = Model.Id, ansid = ans.Id }, null)

                                <br />
                            </div>

                        </div>
           
                    </div>

                
                    count++;
                }
                <br />
            }
        </div>

        
        <br />
        <div>
            @foreach (var tag in Model.Tag)
            {
                string MyTag = @tag.Title;

            <span style="margin-left : 20px">
              
                @Html.ActionLink(MyTag, "Details", "Tags", new { id = tag.TagId }, null)

            </span>
            }
          
        </div>
        <br />
        <div>
            <span style="margin-left:20px"></span>
                @Html.ActionLink("Post A Answer", "CreateAns", "Answers", new { id = Model.Id }, null) |
                @Html.ActionLink("Comment", "Create", "QComments", new { id = Model.Id }, null)

                @if (Model.UserId != @ViewBag.UserId)
                {
        <span>
            &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;  &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;
            &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;  &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;
            @Html.ActionLink("VoteUp", "CreateQUpVote", "MemberHelper", new { id = Model.Id }, null) |
            @Html.ActionLink("VoteDown", "CreateQDownVote", "MemberHelper", new { id = Model.Id }, null)
            <span>&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;Votes : @Model.QVoteCount</span>
        </span>
                }



        </div>

        </div>
          
    <br />
    <br />
</body>
</html>

Views/Questions/Edit.cshtml
@model MyStackOverFlow.Models.Question

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Tilte, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tilte, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tilte, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Qdate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QVoteCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QVoteCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QVoteCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Questions/Index.cshtml
@model IPagedList<MyStackOverFlow.Models.Question>
@using PagedList;
@using PagedList.Mvc;

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Home Page</title>
        <link href="~/Styles.css" rel="stylesheet" type="text/css" />
    </head>

    <body>
        <br />

        <div style="margin-left:120px">
            <h4>
                <b>Recent Questions</b>
            </h4>
        </div>



        <div class="nav1">

            <div style="flex-grow: 4 " class="count">
                <div> @Html.ActionLink("Ask a Question", "Create")</div>
            </div>
            <div>

                @using (Html.BeginForm("NewestFirst", "Questions", FormMethod.Get))
                {
                    <input type="submit" value="NewestFirst" />
                }
            </div>
            <div>
                @using (Html.BeginForm("MostAnsweredFirst", "Questions", FormMethod.Get))
                {
                    <input type="submit" value="MostAnsweredFirst" />
                }
            </div>
        </div>

        <br />
        <div class="main">


            @foreach (var item in Model)
            {<br />
                string Myques = @item.Tilte;
                <div class="questFlex">
                    <div class="ansCount"> Votes : @item.QVoteCount</div>

                    <div class="quest" background-color: #6a8caf style="flex-grow: 6">

                        <span style="margin-left:5px"> @Html.ActionLink(Myques, "Details", "Questions", new { id = item.Id }, null)</span>
                        <div>
                            <span style="margin-left:250px">Posted By:@item.User.UserName</span>
                            @if (item.User.Badge != null)
                            {
                                <img src=@item.User.Badge style="height : 30px;width : 30px;" />
                            } on @item.Qdate.ToShortDateString() &nbsp;



                        </div>

                        <div>
                            @foreach (var tag in item.Tag)
                            {
                                string MyTag = @tag.Title;

                                <span style="margin-left : 20px">

                                    @Html.ActionLink(MyTag, "Details", "Tags", new { id = tag.TagId }, null)

                                </span>
                            }
                            <span style="margin-left:120px">
                               
                                @Html.ActionLink("VoteUp", "CreateQUpVote", "MemberHelper", new { id = item.Id }, null) |
                                @Html.ActionLink("VoteDown", "CreateQDownVote", "MemberHelper", new { id = item.Id }, null)

                            </span>
                        </div>
                      
                    </div>

                    <br />
                </div>
                <br />
            }

        </div>
        <br />

        @Html.PagedListPager(Model, Page => Url.Action("Index", new { Page }),
        new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded })
    </body>


    </html>